export const referenceObjects = {
  'north-park': {
    name: 'ЖК «Северный парк», корпус 3',
    district: 'ЮВАО, Марьино',
    permit: '№ 77-217000-021184-2026',
    programme: 'Программа ПИК-2026',
    status: 'ok',
    statusLabel: 'Соответствует графику',
    stage: 'Земляные работы',
    progress: 38,
    cams: [
      {
        id: 1,
        label: 'Северный въезд',
        feed: 'cam-01-north',
        boxes: [
          { cls: 'exc', conf: '0.97', x: 9, y: 34, w: 20, h: 33 },
          { cls: 'dump', conf: '0.94', x: 37, y: 47, w: 19, h: 25 },
          { cls: 'crane', conf: '0.91', x: 63, y: 16, w: 13, h: 47 },
        ],
      },
      {
        id: 2,
        label: 'Южный въезд',
        feed: 'cam-02-south',
        boxes: [
          { cls: 'dump', conf: '0.92', x: 14, y: 41, w: 22, h: 28 },
          { cls: 'exc', conf: '0.88', x: 48, y: 36, w: 18, h: 31 },
          { cls: 'dump', conf: '0.81', x: 71, y: 52, w: 16, h: 21 },
        ],
      },
      {
        id: 3,
        label: 'Бетонный узел',
        feed: 'cam-03-mixer',
        boxes: [
          { cls: 'mixer', conf: '0.95', x: 22, y: 30, w: 24, h: 34 },
          { cls: 'crane', conf: '0.90', x: 58, y: 12, w: 12, h: 54 },
        ],
      },
    ],
    equipment: [
      { cls: 'exc', name: 'Экскаваторы', count: 3, delta: '+1' },
      { cls: 'dump', name: 'Самосвалы', count: 6, delta: '0' },
      { cls: 'crane', name: 'Башенные краны', count: 2, delta: '0' },
      { cls: 'mixer', name: 'Бетоносмесители', count: 3, delta: '+1' },
    ],
    timeline: [
      { name: 'Земляные работы', plan: 90, fact: 95, dev: '+5 п.п.', status: 'ok' },
      { name: 'Устройство фундамента', plan: 60, fact: 55, dev: '−5 п.п.', status: 'ok' },
      { name: 'Монтаж каркаса', plan: 25, fact: 10, dev: '−15 п.п.', status: 'warn' },
      { name: 'Кровельные работы', plan: 2, fact: 0, dev: '—', status: 'idle' },
    ],
    note: 'За последние 7 дней факт совпадает с планом на 95%. Техника выходит на площадку без пропусков.',
    alarm: null,
    kpi: {
      compliance: '91,4%',
      complianceColor: 'var(--ok)',
      dev: '3 дня',
      devNote: 'накоплено на этапе «Монтаж каркаса»',
      stageNote: 'выполнено 95% планового объёма',
      forecast: '14 марта 2027',
      forecastNote: 'отклонение ±2 дня от плана',
    },
    stages: [
      {
        name: 'Земляные работы',
        plan: '01.06 - 20.07.2026',
        fact: '01.06 - 22.07.2026',
        dev: '+2 дня',
        tone: '',
        status: 'ok',
      },
      {
        name: 'Устройство фундамента',
        plan: '21.07 - 15.09.2026',
        fact: '23.07 - 18.09.2026',
        dev: '+3 дня',
        tone: '',
        status: 'ok',
      },
      {
        name: 'Монтаж каркаса',
        plan: '16.09 - 30.11.2026',
        fact: 'с 20.09, идёт',
        dev: '+6 дней',
        tone: 'late',
        status: 'warn',
      },
      {
        name: 'Кровельные работы',
        plan: '01.12.2026 - 20.01.2027',
        fact: 'не начато',
        dev: '—',
        tone: '',
        status: 'idle',
      },
    ],
  },

  'river-quarter': {
    name: 'ЖК «Речной квартал», корпус 1',
    district: 'ЗАО, Филёвский парк',
    permit: '№ 77-129000-019473-2025',
    programme: 'Программа реновации',
    status: 'warn',
    statusLabel: 'Риск срыва графика',
    stage: 'Монтаж каркаса',
    progress: 61,
    cams: [
      {
        id: 1,
        label: 'Площадка, юг',
        feed: 'cam-04-river',
        boxes: [
          { cls: 'crane', conf: '0.93', x: 26, y: 10, w: 14, h: 56 },
          { cls: 'dump', conf: '0.85', x: 56, y: 50, w: 20, h: 24 },
        ],
      },
      {
        id: 2,
        label: 'Въезд техники',
        feed: 'cam-05-river',
        boxes: [{ cls: 'crane', conf: '0.89', x: 44, y: 22, w: 16, h: 44 }],
      },
    ],
    equipment: [
      { cls: 'exc', name: 'Экскаваторы', count: 1, delta: '−1' },
      { cls: 'dump', name: 'Самосвалы', count: 2, delta: '−2' },
      { cls: 'crane', name: 'Башенные краны', count: 3, delta: '0' },
      { cls: 'mixer', name: 'Бетоносмесители', count: 0, delta: '−1' },
    ],
    timeline: [
      { name: 'Подготовительные работы', plan: 100, fact: 100, dev: '0 п.п.', status: 'ok' },
      { name: 'Земляные работы', plan: 100, fact: 96, dev: '−4 п.п.', status: 'ok' },
      { name: 'Монтаж каркаса', plan: 70, fact: 44, dev: '−26 п.п.', status: 'warn' },
      { name: 'Фасадные работы', plan: 5, fact: 0, dev: '—', status: 'idle' },
    ],
    note: 'Количество техники в кадре падает третьи сутки подряд — минус 62% к средним значениям июля.',
    alarm: {
      title: 'Риск срыва графика на этапе «Монтаж каркаса»',
      text: 'Отставание достигло 6 дней. Система фиксирует снижение количества техники в кадре три дня подряд: 20 августа — 9 единиц, 25 августа — 3 единицы. Требуется выезд на площадку.',
    },
    kpi: {
      compliance: '67,8%',
      complianceColor: 'var(--warn)',
      dev: '6 дней',
      devNote: 'накоплено на этапе «Монтаж каркаса»',
      stageNote: 'выполнено 44% планового объёма',
      forecast: '02 мая 2027',
      forecastNote: 'отклонение +9 дней от плана',
    },
    stages: [
      {
        name: 'Подготовительные работы',
        plan: '01.03 - 20.03.2026',
        fact: '01.03 - 19.03.2026',
        dev: '−1 день',
        tone: 'early',
        status: 'ok',
      },
      {
        name: 'Земляные работы',
        plan: '21.03 - 15.05.2026',
        fact: '21.03 - 18.05.2026',
        dev: '+3 дня',
        tone: '',
        status: 'ok',
      },
      {
        name: 'Монтаж каркаса',
        plan: '16.05 - 10.08.2026',
        fact: 'с 20.05, идёт',
        dev: '+6 дней',
        tone: 'late',
        status: 'warn',
      },
      {
        name: 'Фасадные работы',
        plan: '11.08 - 30.09.2026',
        fact: 'не начато',
        dev: '—',
        tone: '',
        status: 'idle',
      },
    ],
  },

  'kindergarten-214': {
    name: 'Детский сад № 214',
    district: 'САО, Западное Дегунино',
    permit: '№ 77-104000-017902-2025',
    programme: 'Адресная инвестиционная программа',
    status: 'ok',
    statusLabel: 'Соответствует графику',
    stage: 'Отделочные работы',
    progress: 88,
    cams: [
      {
        id: 1,
        label: 'Общий план',
        feed: 'cam-06-kinder',
        boxes: [
          { cls: 'mixer', conf: '0.90', x: 31, y: 38, w: 22, h: 28 },
          { cls: 'dump', conf: '0.83', x: 62, y: 46, w: 18, h: 22 },
        ],
      },
    ],
    equipment: [
      { cls: 'exc', name: 'Экскаваторы', count: 0, delta: '0' },
      { cls: 'dump', name: 'Самосвалы', count: 1, delta: '0' },
      { cls: 'crane', name: 'Башенные краны', count: 0, delta: '0' },
      { cls: 'mixer', name: 'Бетоносмесители', count: 1, delta: '0' },
    ],
    timeline: [
      { name: 'Общестроительные работы', plan: 100, fact: 100, dev: '0 п.п.', status: 'ok' },
      { name: 'Отделочные работы', plan: 85, fact: 88, dev: '+3 п.п.', status: 'ok' },
      { name: 'Благоустройство', plan: 10, fact: 8, dev: '−2 п.п.', status: 'ok' },
    ],
    note: 'Объект выходит на финиш: отделка идёт с небольшим опережением, срыв сроков не прогнозируется.',
    alarm: null,
    kpi: {
      compliance: '96,2%',
      complianceColor: 'var(--ok)',
      dev: '0 дней',
      devNote: 'отклонений не зафиксировано',
      stageNote: 'выполнено 88% планового объёма',
      forecast: '05 октября 2026',
      forecastNote: 'опережение 4 дня к плану',
    },
    stages: [
      {
        name: 'Общестроительные работы',
        plan: '01.02 - 30.04.2026',
        fact: '01.02 - 28.04.2026',
        dev: '−2 дня',
        tone: 'early',
        status: 'ok',
      },
      {
        name: 'Отделочные работы',
        plan: '01.05 - 15.09.2026',
        fact: 'с 01.05, идёт',
        dev: '+1 день',
        tone: '',
        status: 'ok',
      },
      {
        name: 'Благоустройство',
        plan: '16.09 - 05.10.2026',
        fact: 'не начато',
        dev: '—',
        tone: '',
        status: 'idle',
      },
    ],
  },

  'school-1517': {
    name: 'Школа № 1517, корпус 2',
    district: 'СЗАО, Хорошёво-Мнёвники',
    permit: '№ 77-186000-018640-2025',
    programme: 'Адресная инвестиционная программа',
    status: 'warn',
    statusLabel: 'Риск срыва графика',
    stage: 'Кровельные работы',
    progress: 40,
    cams: [
      {
        id: 1,
        label: 'Кровля, ось Б-7',
        feed: 'cam-07-school',
        boxes: [{ cls: 'crane', conf: '0.87', x: 36, y: 18, w: 15, h: 46 }],
      },
    ],
    equipment: [
      { cls: 'exc', name: 'Экскаваторы', count: 0, delta: '0' },
      { cls: 'dump', name: 'Самосвалы', count: 1, delta: '−1' },
      { cls: 'crane', name: 'Башенные краны', count: 1, delta: '0' },
      { cls: 'mixer', name: 'Бетоносмесители', count: 0, delta: '0' },
    ],
    timeline: [
      { name: 'Монтаж каркаса', plan: 100, fact: 97, dev: '−3 п.п.', status: 'ok' },
      { name: 'Кровельные работы', plan: 55, fact: 35, dev: '−20 п.п.', status: 'warn' },
      { name: 'Отделочные работы', plan: 5, fact: 0, dev: '—', status: 'idle' },
    ],
    note: 'Техника на кровле появляется в кадре 2–3 дня в неделю вместо шести — вероятна нехватка бригады.',
    alarm: {
      title: 'Отставание на этапе «Кровельные работы» — 9 дней',
      text: 'Здание должно быть готово к приёмке 1 сентября. При текущем темпе кровля закрывается 28 сентября. Камера 4 не передаёт сигнал с 23 августа — часть работ система не видит.',
    },
    kpi: {
      compliance: '70,5%',
      complianceColor: 'var(--warn)',
      dev: '9 дней',
      devNote: 'накоплено на этапе «Кровельные работы»',
      stageNote: 'выполнено 35% планового объёма',
      forecast: '28 сентября 2026',
      forecastNote: 'отклонение +9 дней от плана',
    },
    stages: [
      {
        name: 'Монтаж каркаса',
        plan: '01.04 - 15.06.2026',
        fact: '01.04 - 20.06.2026',
        dev: '+5 дней',
        tone: '',
        status: 'ok',
      },
      {
        name: 'Кровельные работы',
        plan: '16.06 - 20.08.2026',
        fact: 'с 22.06, идёт',
        dev: '+9 дней',
        tone: 'late',
        status: 'warn',
      },
      {
        name: 'Отделочные работы',
        plan: '21.08 - 25.09.2026',
        fact: 'не начато',
        dev: '—',
        tone: '',
        status: 'idle',
      },
    ],
  },

  'ice-center': {
    name: 'Ледовый центр, Коммунарка',
    district: 'ТиНАО, Сосенское',
    permit: '№ 77-301000-022017-2026',
    programme: 'Спортивные объекты города',
    status: 'ok',
    statusLabel: 'Соответствует графику',
    stage: 'Подготовительные работы',
    progress: 12,
    cams: [
      {
        id: 1,
        label: 'Котлован',
        feed: 'cam-08-ice',
        boxes: [
          { cls: 'exc', conf: '0.95', x: 17, y: 36, w: 21, h: 32 },
          { cls: 'dump', conf: '0.90', x: 48, y: 44, w: 20, h: 26 },
          { cls: 'dump', conf: '0.79', x: 74, y: 49, w: 15, h: 20 },
        ],
      },
    ],
    equipment: [
      { cls: 'exc', name: 'Экскаваторы', count: 2, delta: '+1' },
      { cls: 'dump', name: 'Самосвалы', count: 3, delta: '+2' },
      { cls: 'crane', name: 'Башенные краны', count: 0, delta: '0' },
      { cls: 'mixer', name: 'Бетоносмесители', count: 0, delta: '0' },
    ],
    timeline: [
      { name: 'Подготовительные работы', plan: 15, fact: 12, dev: '−3 п.п.', status: 'ok' },
      { name: 'Земляные работы', plan: 0, fact: 0, dev: '—', status: 'idle' },
    ],
    note: 'Техника вышла на площадку в плановую дату. Данных пока мало для оценки темпа.',
    alarm: null,
    kpi: {
      compliance: '98,6%',
      complianceColor: 'var(--ok)',
      dev: '0 дней',
      devNote: 'отклонений не зафиксировано',
      stageNote: 'выполнено 12% планового объёма',
      forecast: 'Расчёт с октября',
      forecastNote: 'нужен месяц наблюдений для прогноза',
    },
    stages: [
      {
        name: 'Подготовительные работы',
        plan: '01.08 - 30.09.2026',
        fact: 'с 01.08, идёт',
        dev: '0 дней',
        tone: '',
        status: 'ok',
      },
    ],
  },

  'tennis-center': {
    name: 'Теннисный центр',
    district: 'СЗАО, Мнёвниковская пойма',
    permit: 'ожидается 12.09.2026',
    programme: 'Спортивные объекты города',
    status: 'idle',
    statusLabel: 'Работы не начаты',
    stage: 'Ожидает начала работ',
    progress: 0,
    cams: [],
    connectDate: '01.10.2026',
    equipment: [
      { cls: 'exc', name: 'Экскаваторы', count: 0, delta: '0' },
      { cls: 'dump', name: 'Самосвалы', count: 0, delta: '0' },
      { cls: 'crane', name: 'Башенные краны', count: 0, delta: '0' },
      { cls: 'mixer', name: 'Бетоносмесители', count: 0, delta: '0' },
    ],
    timeline: [{ name: 'Подготовительные работы', plan: 0, fact: 0, dev: '—', status: 'idle' }],
    note: 'Видеопотоки подключатся автоматически в день старта работ, 1 октября 2026 года.',
    alarm: null,
    kpi: {
      compliance: '—',
      complianceColor: 'var(--ink-3)',
      dev: '—',
      devNote: 'работы ещё не начаты',
      stageNote: 'плановый старт 01.10.2026',
      forecast: '—',
      forecastNote: 'график считается после старта',
    },
    stages: [
      {
        name: 'Подготовительные работы',
        plan: '01.10 - 20.11.2026',
        fact: 'не начато',
        dev: '—',
        tone: '',
        status: 'idle',
      },
    ],
  },
} as const;
